kitchen/urls.py
from django.urls import path

from kitchen.views import (
    index,
    CookListView,
    CookDetailView,
    CookCreateView,
    CookUpdateView,
    CookDeleteView,
    DishTypeListView,
    DishTypeDetailView,
    DishTypeCreateView,
    DishTypeUpdateView,
    DishTypeDeleteView,
    DishListView,
    DishDetailView,
    DishCreateView,
    DishUpdateView,
    DishDeleteView,
    DishAssignOrDeleteUpdateView,
)

urlpatterns = [
    path("", index, name="index"),
    path(
        "cooks/",
        CookListView.as_view(),
        name="cook-list"
    ),
    path(
        "cooks/<int:pk>/",
        CookDetailView.as_view(),
        name="cook-detail"
    ),
    path(
        "cooks/create",
        CookCreateView.as_view(),
        name="cook-create"
    ),
    path(
        "cooks/<int:pk>/update/",
        CookUpdateView.as_view(),
        name="cook-update",
    ),
    path(
        "cooks/<int:pk>/delete/",
        CookDeleteView.as_view(),
        name="cook-delete",
    ),
    path(
        "dish-types/",
        DishTypeListView.as_view(),
        name="dish-type-list"
    ),
    path(
        "dish-types/<int:pk>/",
        DishTypeDetailView.as_view(),
        name="dish-type-detail"),
    path(
        "dish-types/create/",
        DishTypeCreateView.as_view(),
        name="dish-type-create",
    ),
    path(
        "dish-types/<int:pk>/update/",
        DishTypeUpdateView.as_view(),
        name="dish-type-update",
    ),
    path(
        "dish-types/<int:pk>/delete/",
        DishTypeDeleteView.as_view(),
        name="dish-type-delete",
    ),
    path(
        "dishes/",
        DishListView.as_view(),
        name="dish-list"
    ),
    path(
        "dishes/<int:pk>/",
        DishDetailView.as_view(),
        name="dish-detail"
    ),
    path(
        "dishes/create/",
        DishCreateView.as_view(),
        name="dish-create",
    ),
    path(
        "dishes/<int:pk>/update/",
        DishUpdateView.as_view(),
        name="dish-update",
    ),
    path(
        "dishes/<int:pk>/delete/",
        DishDeleteView.as_view(),
        name="dish-delete",
    ),
    path(
        "dishes/<int:pk>/assign-or-delete/",
        DishAssignOrDeleteUpdateView.as_view(),
        name="dish-assign-or-delete",
    ),
]

app_name = "kitchen"

restaurant_kitchen_service/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", include("kitchen.urls", namespace="kitchen")),
]

kitchen/models.py
from django.conf import settings
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse


class Cook(AbstractUser):
    years_of_experience = models.IntegerField(null=True, blank=True)

    class Meta:
        ordering = ["username"]

    def __str__(self):
        return f"{self.username} ({self.first_name} {self.last_name})"

    def get_absolute_url(self):
        return reverse("kitchen:cook-detail", kwargs={"pk": self.pk})


class DishType(models.Model):
    name = models.CharField(max_length=255, unique=True)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("kitchen:dish-type-detail", kwargs={"pk": self.pk})


class Dish(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    price = models.DecimalField(max_digits=7, decimal_places=2)
    dish_type = models.ForeignKey(
        DishType, on_delete=models.CASCADE, related_name="dishes"
    )
    cooks = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name="dishes"
    )

    class Meta:
        verbose_name_plural = "dishes"
        ordering = ["name"]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("kitchen:dish-detail", kwargs={"pk": self.pk})

kitchen/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError

from kitchen.models import Cook, Dish


class CookCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Cook
        fields = UserCreationForm.Meta.fields + (
            "first_name",
            "last_name",
            "years_of_experience",
        )

    def clean(self):
        validate_years_of_experience(self.cleaned_data)


class CookUpdatingForm(forms.ModelForm):
    class Meta(UserCreationForm.Meta):
        model = Cook
        fields = ("username", "first_name", "last_name", "years_of_experience")

    def clean(self):
        validate_years_of_experience(self.cleaned_data)


def validate_years_of_experience(cleaned_data):
    years_of_experience = cleaned_data["years_of_experience"]

    if years_of_experience < 0 or years_of_experience > 80:
        raise ValidationError(
            "Number of years of experience must be " "between 0 and 80"
        )

    return years_of_experience


class CookSearchForm(forms.Form):
    username_ = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={"placeholder": "Search by username..."}
        ),
    )


class DishSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={"placeholder": "Search by dish name..."}
        ),
    )


class DishTypeSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={"placeholder": "Search by dish type name..."}
        ),
    )


class DishAssignOrDeleteForm(forms.ModelForm):
    class Meta:
        model = Dish
        fields = []

kitchen/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views import generic

from kitchen.forms import (
    CookCreationForm,
    CookUpdatingForm,
    CookSearchForm,
    DishTypeSearchForm,
    DishSearchForm,
    DishAssignOrDeleteForm,
)
from kitchen.models import Cook, Dish, DishType


@login_required
def index(request):
    """View function for the home page of the site."""

    num_cooks = Cook.objects.count()
    num_dishes = Dish.objects.count()
    num_dish_types = DishType.objects.count()

    num_visits = request.session.get("num_visits", 0)
    request.session["num_visits"] = num_visits + 1

    context = {
        "num_cooks": num_cooks,
        "num_dishes": num_dishes,
        "num_dish_types": num_dish_types,
        "num_visits": num_visits + 1,
    }

    return render(request, "kitchen/index.html", context=context)


class CookListView(LoginRequiredMixin, generic.ListView):
    model = Cook
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(CookListView, self).get_context_data(**kwargs)
        username = self.request.GET.get("username_", "")

        context["search_form"] = CookSearchForm(
            initial={"username_": username}
        )

        return context

    def get_queryset(self):
        queryset = Cook.objects.all()
        form = CookSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(
                username__icontains=form.cleaned_data["username_"]
            )

        return queryset


class CookDetailView(LoginRequiredMixin, generic.DetailView):
    model = Cook
    queryset = Cook.objects.prefetch_related("dishes__dish_type")


class CookCreateView(generic.CreateView):
    model = Cook
    form_class = CookCreationForm


class CookUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Cook
    form_class = CookUpdatingForm


class CookDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Cook
    success_url = reverse_lazy("kitchen:cook-list")


class DishTypeListView(LoginRequiredMixin, generic.ListView):
    model = DishType
    paginate_by = 5
    template_name = "kitchen/dish_type_list.html"
    context_object_name = "dish_type_list"

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(DishTypeListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")

        context["search_form"] = DishTypeSearchForm(initial={"name": name})

        return context

    def get_queryset(self):
        queryset = DishType.objects.all()
        form = DishTypeSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(name__icontains=form.cleaned_data["name"])

        return queryset


class DishTypeDetailView(LoginRequiredMixin, generic.DetailView):
    model = DishType
    template_name = "kitchen/dish_type_detail.html"
    context_object_name = "dish_type_detail"


class DishTypeCreateView(LoginRequiredMixin, generic.CreateView):
    model = DishType
    fields = "__all__"
    template_name = "kitchen/dish_type_form.html"
    success_url = reverse_lazy("kitchen:dish-type-list")


class DishTypeUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = DishType
    fields = "__all__"
    template_name = "kitchen/dish_type_form.html"
    context_object_name = "dish_type_detail"
    success_url = reverse_lazy("kitchen:dish-type-list")


class DishTypeDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = DishType
    template_name = "kitchen/dish_type_confirm_delete.html"
    context_object_name = "dish_type_detail"
    success_url = reverse_lazy("kitchen:dish-type-list")


class DishListView(LoginRequiredMixin, generic.ListView):
    model = Dish
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(DishListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")

        context["search_form"] = DishSearchForm(initial={"name": name})

        return context

    def get_queryset(self):
        queryset = Dish.objects.all()
        form = DishSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(name__icontains=form.cleaned_data["name"])

        return queryset


class DishDetailView(LoginRequiredMixin, generic.DetailView):
    model = Dish
    queryset = Dish.objects.prefetch_related("cooks__dishes")


class DishCreateView(LoginRequiredMixin, generic.CreateView):
    model = Dish
    fields = "__all__"


class DishUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Dish
    fields = "__all__"


class DishDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Dish
    success_url = reverse_lazy("kitchen:dish-list")


class DishAssignOrDeleteUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Dish
    form_class = DishAssignOrDeleteForm

    def post(self, request, *args, **kwargs):
        user = request.user
        pk = kwargs.get("pk")
        dish = get_object_or_404(Dish, id=pk)

        if user in dish.cooks.all():
            dish.cooks.remove(user)
        else:
            dish.cooks.add(user)

        return redirect("kitchen:dish-detail", pk)

templates/kitchen/cook_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete cook</h1>
  <p>Are you sure you want to delete the cook: {{ cook }}?</p>

  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes" class="btn btn-danger">
    <a class="btn btn-primary" href="{% url 'kitchen:cook-list' %}">Cancel</a>
  </form>
{% endblock %}

templates/kitchen/cook_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Username: {{ cook.username }}
    <a href="{% url 'kitchen:cook-delete' pk=cook.id %}" class="btn btn-danger link-to-page">
      Delete
    </a>

    <a href="{% url 'kitchen:cook-update' pk=cook.id %}" class="btn btn-secondary link-to-page">
      Update
    </a>
  </h1>

  <p><strong>First name:</strong> {{ cook.first_name }}</p>
  <p><strong>Last name:</strong> {{ cook.last_name }}</p>
  <p><strong>Years of experience:</strong> {{ cook.years_of_experience }}</p>
  <p><strong>Is staff:</strong> {{ cook.is_staff }}</p>

  <div class="ml-3">
    <h4>Dishes</h4>

    {% for dish in cook.dishes.all %}
        <hr>
        <p><strong>Name:</strong> {{ dish.name }}</p>
        <p><strong>Dish Type:</strong> {{ dish.dish_type.name }}</p>
        <p><strong>Description:</strong> {{ dish.description }}</p>
        <p><strong>Price:</strong> ${{ dish.price }}</p>
        <p class="text-muted"><strong>Id:</strong> {{dish.id}}</p>

    {% empty %}
      <p>No dishes!</p>
    {% endfor %}
  </div>
{% endblock %}

templates/kitchen/cook_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} cook</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/kitchen/cook_list.html
{% extends "base.html" %}
{% block content %}
    <h1>
      Cook List
      <a href="{% url "kitchen:cook-create" %}" class="btn btn-primary link-to-page">
          Create
      </a>
    </h1>

    {% include "includes/search_form.html" %}

    {% if cook_list %}
      <table class="table">
        <tr>
          <th>ID</th>
          <th>Username</th>
          <th>First name</th>
          <th>Last name</th>
          <th>License number</th>
        </tr>

        {% for cook in cook_list %}
          <tr>
            <td>{{ cook.id }}</td>
            <td><a href="{{ cook.get_absolute_url }}">{{ cook.username }} {% if user == cook %} (Me){% endif %}</a></td>
            <td>{{ cook.first_name }}</td>
            <td>{{ cook.last_name }}</td>
            <td>{{ cook.license_number }}</td>
          </tr>
        {% endfor %}
      </table>
    {% else %}
      <p>There are no cooks in kitchen</p>
    {% endif %}
{% endblock %}

templates/kitchen/dish_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete dish</h1>
  <p>Are you sure you want to delete the dish: {{ dish }}?</p>

  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes" class="btn btn-danger">
    <a class="btn btn-primary" href="{% url 'kitchen:dish-list' %}">Cancel</a>
  </form>
{% endblock %}

templates/kitchen/dish_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>
    {{ dish.name }}
    <a href="{% url 'kitchen:dish-delete' pk=dish.id %}" class="btn btn-danger link-to-page">
      Delete
    </a>

    <a href="{% url 'kitchen:dish-update' pk=dish.id %}" class="btn btn-secondary link-to-page">
      Update
    </a>
  </h1>

  <p><strong>Dish Type:</strong> {{ dish.dish_type.name }}</p>
  <p><strong>Description:</strong> {{ dish.description }}</p>
  <p><strong>Price:</strong> ${{ dish.price }}</p>
  <p class="text-muted"><strong>Id:</strong> {{dish.id}}</p>

  <div class="ml-3">
    <h4>
      Cooks
      {% if user in dish.cooks.all %}
        <a
            href="{% url 'kitchen:dish-assign-or-delete' pk=dish.id %}"
            class="btn btn-danger link-to-page mr-5"
            style="float: right"
        >
          Delete me from this dish
        </a>
      {% else %}
        <a
            href="{% url 'kitchen:dish-assign-or-delete' pk=dish.id %}"
            class="btn btn-success link-to-page mr-5"
            style="float: right"
        >
          Assign me to this dish
        </a>
      {% endif %}
    </h4>

    {% for cook in dish.cooks.all %}
      <hr>
      <p><strong>First name:</strong> {{ cook.first_name }}</p>
      <p><strong>Last name:</strong> {{ cook.last_name }}</p>
      <p><strong>Years of experience:</strong> {{ cook.years_of_experience }}</p>
      <p><strong>Is staff:</strong> {{ cook.is_staff }}</p>

    {% empty %}
      <p>No cooks!</p>
    {% endfor %}
  </div>
{% endblock %}

templates/kitchen/dish_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} dish</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/kitchen/dish_list.html
{% extends "base.html" %}
{% block content %}
    <h1>
      Dish List
      <a href="{% url "kitchen:dish-create" %}" class="btn btn-primary link-to-page">
        Create
      </a>
    </h1>

    {% include "includes/search_form.html" %}

    {% if dish_list %}
      <table class="table">
        <tr>
          <th>ID</th>
          <th>Name</th>
          <th>Dish Type</th>
        </tr>
        {% for dish in dish_list %}
          <tr>
            <td>{{ dish.id }}</td>
            <td><a href="{{ dish.get_absolute_url }}">{{ dish.name }}</a></td>
            <td>{{ dish.dish_type }}</td>
          </tr>
        {% endfor %}
      </table>
    {% else %}
      <p>There are no dishes in kitchen</p>
    {% endif %}
{% endblock %}

templates/kitchen/dish_type_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete dish type</h1>
  <p>Are you sure you want to delete the dish type: {{ dish_type_detail }}?</p>
  <p><i>All Dishes of this dish type will be also deleted!</i></p>

  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes" class="btn btn-danger">
    <a class="btn btn-primary" href="{% url 'kitchen:dish-type-list' %}">Cancel</a>
  </form>
{% endblock %}

templates/kitchen/dish_type_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>
    {{ dish_type_detail.name }}
    <a href="{% url 'kitchen:dish-type-delete' pk=dish_type_detail.id %}" class="btn btn-danger link-to-page">
      Delete
    </a>

    <a href="{% url 'kitchen:dish-type-update' pk=dish_type_detail.id %}" class="btn btn-secondary link-to-page">
      Update
    </a>
  </h1>

  <div class="ml-3">
    <h4>Dishes</h4>

    {% for dish in dish_type_detail.dishes.all %}
      <hr>
      <p><strong>Name:</strong> {{ dish.name }}</p>
      <p><strong>Description:</strong> {{ dish.description }}</p>
      <p><strong>Price:</strong> ${{ dish.price }}</p>
      <p class="text-muted"><strong>Id:</strong> {{dish.id}}</p>

    {% empty %}
      <p>No dishes!</p>
    {% endfor %}
  </div>
{% endblock %}

templates/kitchen/dish_type_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} dish type</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/kitchen/dish_type_list.html
{% extends "base.html" %}
{% block content %}
    <h1>
      Dish Type List
      <a href="{% url "kitchen:dish-type-create" %}" class="btn btn-primary link-to-page">
        Create
      </a>
    </h1>

    {% include "includes/search_form.html" %}

    {% if dish_type_list %}
      <table class="table">
        <tr>
          <th>ID</th>
          <th>Name</th>
        </tr>
        {% for dish_type in dish_type_list %}
          <tr>
            <td>{{ dish_type.id }}</td>
            <td><a href="{{ dish_type.get_absolute_url }}">{{ dish_type.name }}</a></td>
          </tr>
        {% endfor %}
      </table>
    {% else %}
      <p>There are no dish types in kitchen</p>
    {% endif %}
{% endblock %}

templates/kitchen/dish_view.html
{% extends "base.html" %}
{% block content %}
    <h1>Dish Type List</h1>
    {% if dish_type_list %}
      <ul>
        {% for dish_type in dish_type_list %}
          <li>{{ dish_type }}</li>
        {% endfor %}
      </ul>
    {% else %}
      <p>There are no dish types in kitchen</p>
    {% endif %}
{% endblock %}

templates/kitchen/index.html
{% extends "base.html" %}

{% block content %}
    <h1>Restaurant Kitchen Service Home</h1>
    <p>Welcome to Best Kitchen Ever!</p>
    <h2>Dynamic content</h2>
    <p>The Restaurant Kitchen service has the following record counts:</p>
    <ul>
        <li><strong>Cooks:</strong> {{ num_cooks }}</li>
        <li><strong>Dishes:</strong> {{ num_dishes }}</li>
        <li><strong>Dish Types:</strong> {{ num_dish_types }}</li>
    </ul>

    <p>You have visited this page
        {{ num_visits }} time{{ num_visits|pluralize }}.
    </p>

{% endblock %}